apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: app-boas-vindas

images:
- name: app-boas-vindas
  newName: nandocloud/app-boas-vindas
  newTag: 1dbd566075dccc96b3908f5e8c312efd0d0e1cfa
- name: react-application
  newName: app-boas-vindas
  newTag: latest
